language: node_js
node_js:
    - "6.9.0"
    - "8.5.0"

install:
    - npm install .
    - npm install kelda/deployment-engine-downloader && ./node_modules/.bin/kelda-downloader

before_script:
    - npm install -g gulp-cli

script:
    - gulp lint
    - ./kelda inspect ./meanExample.js graphviz

notifications:
    slack:
        secure: Om39285ocynl45TKYgRtrHGl9mgzyjVjFFgB5oSa6Joel6CZRTN2YnyLKqukI14FXHCp6uz4I+tawzO816I1K5teugEb2QV+I1D1dd4gqtOggnvhIBgDMg7HaastIHIB2CJF4nXMOM2MHQLJB3hE7DhuZyomLv8/cuBBAAgzVo1KQJDHGPSABGja5q7VW7K/yCVKDMwKpIB/236kGAWBdcmtBwA4JTnDD31tHhujAi7JgyJMO7APhShvrX6v5X1CUATsqNmzTW+2C//ATcY4SrEd0K9Xc+NO0OMXV/1ezdkBd0OsXyFRNih5lzTehXMe3GIpNYERbuuCyk1sOAUvIoLP2EJbBpjsMnbkDlXWja3hBV1uExnQZ8U54jLDXXcMtrbBc9SmME44Thwz0atJIzOU+JgWbPcJaiTNLpNsQxw/62VTojfPJvgk79NkkzpAI6ysiDFGEsodFm75004G63tutcHOJ3FNdyTaH1Au/0BVhIoUihyWnQA/YQaLdnPeRxgKTwBZ2HS3ZFQ3TNmzViZCfdzgQaRUMoXY+1BAJFONK0jzf8jWwCWeHT/YRqvZsgfLMCY3/xEfcMvVxR2SiHr/9U88puWxOKjHObjf57vkeiokbxdUqQyBbqTPGFlYBqQ00yUE1fn+wh9IutQ2EdkAmDS0wQEZR7x+4D/V+vQ=
